pub enum BlockTypes {
  Reserved = 0x00000000,
  InterfaceDescriptionBlock = 0x00000001,
  PacketBlock = 0x00000002,
  SimplePacketBlock = 0x00000003,
  NameResolutionBlock = 0x00000004,
  InterfaceStatisticsBlock = 0x00000005,
  EnhancedPacketBlock = 0x00000006,
  IrigTimestampBlock = 0x00000007,
  Arinc429Block = 0x00000008,
  SystemdJournalExportBlock = 0x00000009,
  DecryptionSecretsBlock = 0x0000000a,
  HoneProjectMachineInfoBlock = 0x00000101,
  HoneProjectConnectionEventBlock = 0x00000102,
  SysdigMachineInfoBlock = 0x00000201,
  SysdigProcessInfoBlock = 0x00000202,
  SysdigFdListBlock = 0x00000203,
  SysdigEventBlock = 0x00000204,
  SysdigInterfaceListBlock = 0x00000205,
  SysdigUserListBlock = 0x00000206,
  SysdigProcessInfoBlockV2 = 0x00000207,
  SysdigEventBlockWithFlags = 0x00000208,
  SysdigProcessInfoBlockV3 = 0x00000209,
  SysdigProcessInfoBlockV4 = 0x00000210,
  SysdigProcessInfoBlockV5 = 0x00000211,
  SysdigProcessInfoBlockV6 = 0x00000212,
  SysdigProcessInfoBlockV7 = 0x00000213,
  CustomBlockRewritersCanCopy = 0x00000BAD,
  CustomBlockRewritersShouldNotCopy = 0x40000BAD,
  SectionHeaderBlock = 0x0A0D0D0A,
  Unknown,
}

pub fn block_type_str(block_type: &BlockTypes) -> String {
  match block_type {
    BlockTypes::InterfaceDescriptionBlock => "Interface Description Block".to_owned(),
    BlockTypes::PacketBlock => "Packet Block".to_owned(),
    BlockTypes::SimplePacketBlock => "Simple Packet Block".to_owned(),
    BlockTypes::NameResolutionBlock => "Name Resolution Block".to_owned(),
    BlockTypes::InterfaceStatisticsBlock => "Interface Statistics Block".to_owned(),
    BlockTypes::EnhancedPacketBlock => "Enhanced Packet Block".to_owned(),
    BlockTypes::IrigTimestampBlock => "IRIG Timestamp/Socket Aggregation Event Block".to_owned(),
    BlockTypes::Arinc429Block => "AFDX Encapsulation Information Block".to_owned(),
    BlockTypes::SystemdJournalExportBlock => "systemd Journal Export Block".to_owned(),
    BlockTypes::DecryptionSecretsBlock => "Decryption Secrets Block".to_owned(),
    BlockTypes::HoneProjectMachineInfoBlock => "Hone Project Machine Info Block".to_owned(),
    BlockTypes::HoneProjectConnectionEventBlock => "Hone Project Connection Event Block".to_owned(),
    BlockTypes::SysdigMachineInfoBlock => "Sysdig Machine Info Block".to_owned(),
    BlockTypes::SysdigProcessInfoBlock => "Sysdig Process Info Block, version 1".to_owned(),
    BlockTypes::SysdigFdListBlock => "Sysdig FD List Block".to_owned(),
    BlockTypes::SysdigEventBlock => "Sysdig Event Block".to_owned(),
    BlockTypes::SysdigInterfaceListBlock => "Sysdig Interface List Block".to_owned(),
    BlockTypes::SysdigUserListBlock => "Sysdig User List Block".to_owned(),
    BlockTypes::SysdigProcessInfoBlockV2 => "Sysdig Process Info Block, version 2".to_owned(),
    BlockTypes::SysdigEventBlockWithFlags => "Sysdig Event Block with flags".to_owned(),
    BlockTypes::SysdigProcessInfoBlockV3 => "Sysdig Process Info Block, version 3".to_owned(),
    BlockTypes::SysdigProcessInfoBlockV4 => "Sysdig Process Info Block, version 4".to_owned(),
    BlockTypes::SysdigProcessInfoBlockV5 => "Sysdig Process Info Block, version 5".to_owned(),
    BlockTypes::SysdigProcessInfoBlockV6 => "Sysdig Process Info Block, version 6".to_owned(),
    BlockTypes::SysdigProcessInfoBlockV7 => "Sysdig Process Info Block, version 7".to_owned(),
    BlockTypes::CustomBlockRewritersCanCopy => {
      "Custom Block that rewriters can copy into new files".to_owned()
    }
    BlockTypes::CustomBlockRewritersShouldNotCopy => {
      "Custom Block that rewriters should not copy into new files".to_owned()
    }
    BlockTypes::SectionHeaderBlock => "Section Header Block".to_owned(),
    _ => "Unknown".to_owned(),
  }
}

impl From<u32> for BlockTypes {
  fn from(n: u32) -> Self {
    match n {
      0x00000000 => BlockTypes::Reserved,
      0x00000001 => BlockTypes::InterfaceDescriptionBlock,
      0x00000002 => BlockTypes::PacketBlock,
      0x00000003 => BlockTypes::SimplePacketBlock,
      0x00000004 => BlockTypes::NameResolutionBlock,
      0x00000005 => BlockTypes::InterfaceStatisticsBlock,
      0x00000006 => BlockTypes::EnhancedPacketBlock,
      0x00000007 => BlockTypes::IrigTimestampBlock,
      0x00000008 => BlockTypes::Arinc429Block,
      0x00000009 => BlockTypes::SystemdJournalExportBlock,
      0x0000000a => BlockTypes::DecryptionSecretsBlock,
      0x00000101 => BlockTypes::HoneProjectMachineInfoBlock,
      0x00000102 => BlockTypes::HoneProjectConnectionEventBlock,
      0x00000201 => BlockTypes::SysdigMachineInfoBlock,
      0x00000202 => BlockTypes::SysdigProcessInfoBlock,
      0x00000203 => BlockTypes::SysdigFdListBlock,
      0x00000204 => BlockTypes::SysdigEventBlock,
      0x00000205 => BlockTypes::SysdigInterfaceListBlock,
      0x00000206 => BlockTypes::SysdigUserListBlock,
      0x00000207 => BlockTypes::SysdigProcessInfoBlockV2,
      0x00000208 => BlockTypes::SysdigEventBlockWithFlags,
      0x00000209 => BlockTypes::SysdigProcessInfoBlockV3,
      0x00000210 => BlockTypes::SysdigProcessInfoBlockV4,
      0x00000211 => BlockTypes::SysdigProcessInfoBlockV5,
      0x00000212 => BlockTypes::SysdigProcessInfoBlockV6,
      0x00000213 => BlockTypes::SysdigProcessInfoBlockV7,
      0x00000BAD => BlockTypes::CustomBlockRewritersCanCopy,
      0x40000BAD => BlockTypes::CustomBlockRewritersShouldNotCopy,
      0x0A0D0D0A => BlockTypes::SectionHeaderBlock,
      _ => BlockTypes::Unknown,
    }
  }
}
